import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { BettingProvider } from "@/context/BettingContext";
import { BetSlip } from "@/components/betting/BetSlip";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen flex flex-col font-sans text-foreground bg-background`}
      >
        <BettingProvider>
          <Header />
          <main className="flex-1">
            {children}
          </main>
          <Footer />
          <BetSlip />
        </BettingProvider>
      </body>
    </html>
  );
}
